// Build-time only. Workers import standalone validators, never Ajv's code generator.
import { readFileSync, writeFileSync } from "node:fs";
import Ajv from "ajv";
import standaloneCode from "ajv/dist/standalone/index.js";

const source = new URL("./wire-schemas.json", import.meta.url);
const destination = new URL("./wire-validators.mjs", import.meta.url);
const schema = JSON.parse(readFileSync(source, "utf8"));
const ajv = new Ajv({
	strict: true,
	ownProperties: true,
	allErrors: false,
	coerceTypes: false,
	removeAdditional: false,
	useDefaults: false,
	// Bounds are in the ASCII regexes: no runtime length/equality helper imports.
	code: { source: true, esm: true, lines: true },
});
ajv.addSchema(schema);
const deployment = JSON.parse(readFileSync(new URL("./deployment-schema.json", import.meta.url), "utf8"));
ajv.addSchema(deployment);
const code = "// Generated by shared/v3/compile-schemas.mjs. Do not edit.\n" + standaloneCode(ajv, {
	validateTransferShape: `${schema.$id}#/definitions/transferRequest`,
	validateEnvironmentShape: `${schema.$id}#/definitions/environment`,
	validateDeploymentShape: `${deployment.$id}#/definitions/manifest`,
	validateCreationShape: `${deployment.$id}#/definitions/creation`,
});
if (/\brequire\s*\(|\beval\s*\(|new Function\b/.test(code)) throw new Error("Validator is not Workers-safe standalone code");
if (process.argv.includes("--check")) {
	if (readFileSync(destination, "utf8").replace(/\r\n/g, "\n") !== code) throw new Error("V3 wire validators are stale");
	console.log("V3 standalone schemas match generated validators");
} else {
	writeFileSync(destination, code);
	console.log("Generated V3 standalone wire validators");
}
