/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=v3/wrangler.jsonc --env-file=.dev.vars.example --include-runtime=false --strict-vars=false --env-interface=WalletCoreV3Bindings v3/bindings.d.ts` (hash: b53bbbb27a7f91c54e5638d87ff16962)
interface __BaseEnv_WalletCoreV3Bindings {
	WALLET_DB: D1Database;
	CREATION_JOBS: Queue;
	CREATION_QUEUE_NAME: string;
	GATOPAGO_ENVIRONMENT: string;
	FIREBASE_PROJECT_ID: string;
	FIREBASE_WEB_API_KEY: string;
	TURNSTILE_SECRET_KEY: string;
	AUTH_RATE_LIMIT_PEPPER: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../src/v3/index");
	}
	interface Env extends __BaseEnv_WalletCoreV3Bindings {}
}
interface WalletCoreV3Bindings extends __BaseEnv_WalletCoreV3Bindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CREATION_QUEUE_NAME" | "GATOPAGO_ENVIRONMENT" | "FIREBASE_PROJECT_ID" | "FIREBASE_WEB_API_KEY" | "TURNSTILE_SECRET_KEY" | "AUTH_RATE_LIMIT_PEPPER">> {}
}
